### ISSUE TITLE
Crash after selecting DXM power supplies

### ISSUE THREAD

**Issue by m4tt-willi4ms** [mjsh635/TubeConditioningRig#2]
Odd error when running the `.jar` file, after having specified a number of DXM power supplies and clicking "Continue with these settings":

> In WindowMaker
> java.io.InvalidClassException: ConditioningPackage.Settings; local class incompatible: stream classdesc serialVersionUID = -2802102107386791587, local class serialVersionUID = 1
> 	at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:689)
> 	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1982)
> 	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1851)
> 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2139)
> 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1668)
> 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:482)
> 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:440)
> 	at ConditioningPackage.SettingsHandler.loadSettings(SettingsHandler.java:61)
> 	at ConditioningPackage.SettingsHandler.<init>(SettingsHandler.java:39)
> 	at ConditioningPackage.SupplyScreen.<init>(SupplyScreen.java:63)
> 	at ConditioningPackage.SetupFrame.WindowMaker(SetupFrame.java:548)
> 	at ConditioningPackage.SetupFrame.ContinueButtonActionPerformed(SetupFrame.java:459)
> 	at ConditioningPackage.SetupFrame.access$0(SetupFrame.java:434)
> 	at ConditioningPackage.SetupFrame$1.actionPerformed(SetupFrame.java:369)
> 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
> 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
> 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
> 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
> 	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
> 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
> 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
> 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
> 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
> 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
> 	at ConditioningPackage.SupplyScreen.Load_Settings(SupplyScreen.java:1957)
> 	at ConditioningPackage.SupplyScreen.<init>(SupplyScreen.java:64)
> 	at ConditioningPackage.SetupFrame.WindowMaker(SetupFrame.java:548)
> 	at ConditioningPackage.SetupFrame.ContinueButtonActionPerformed(SetupFrame.java:459)
> 	at ConditioningPackage.SetupFrame.access$0(SetupFrame.java:434)
> 	at ConditioningPackage.SetupFrame$1.actionPerformed(SetupFrame.java:369)
> 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
> 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
> 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
> 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
> 	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
> 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
> 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
> 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
> 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
> 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Seems to have to do with the parsing of the `Settings.obj` file? Any insight into what could be causing this?

**Comment by m4tt-willi4ms** [comment]
Hope all is well @mjsh635 ! Thought I'd chat here about this, rather than emailing :)
